### ISSUE TITLE
TransactionVerify returns isValid false when using the default minimum difficulty value

### ISSUE THREAD

**Issue by marcel-silva** [benjaminsky/DataWillPersist#1]
Hi, I just read your great article on medium website. Well done!

However, when using the "default minimum difficulty" value of “0xFFFFFF”, 
TransactionVerify returns IsValid=0.

Example:

/* start */
EXEC [dbo].[StartFromScratch]
DECLARE @UserID INT
EXEC @UserID = [dbo].[UserAdd] 'Bob'
EXEC @UserID = [dbo].[UserAdd] 'Alice'
EXEC [dbo].[MessageAdd] 1000,1001,'Test','This will be a single message block'
EXEC BlockAdd
EXEC BlockMine 0xFFFFFF -- or just leave it empty
EXEC TransactionVerify 20000
/* end */

Thanks

**Comment by benjaminsky** [comment]
This was due to a too small initial value for `@Signature` in the `BlockMine` proc.  I've set it to `0xFFFFFFFF` which is larger than `@Difficulty` can ever be since it's `VARBINARY(3)`.  Tested the fix with your example and it's working now.  Thanks for raising the issue and for your interest in my post!

**Comment by marcel-silva** [comment]
Hey thanks. It works like a charm now. :)

I have some other questions, wheres the best place to contact you?
